package com.petstore.models;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.List;

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class Pet {
    private long id;                // Unique identifier of the pet
    private Category category;      // Category information of the pet
    private String name;            // Name of the pet
    private List<String> photoUrls; // List of photo URLs of the pet
    private List<Tag> tags;         // List of tags associated with the pet
    private PetStatus status;          // Status of the pet (e.g., available, pending, sold)

    @Getter
    @Setter
    @AllArgsConstructor
    @NoArgsConstructor
    public static class Category {
        private long id;       // Unique identifier of the category
        private String name;   // Name of the category
    }

    @Getter
    @Setter
    @AllArgsConstructor
    @NoArgsConstructor
    public static class Tag {
        private long id;       // Unique identifier of the tag
        private String name;   // Name of the tag
    }

    public enum PetStatus {
        AVAILABLE,
        PENDING,
        SOLD
    }

    public  PetStatus fromValue(String value) {
        return PetStatus.valueOf(value.toUpperCase());
    }

    public void setStatus(String status) {
        this.status = fromValue(status);
    }
    // Constructors, getters, and setters generated by Lombok

    @Override
    public String toString() {
        return "Pet{" +
                "id=" + id +
                ", category=" + category +
                ", name='" + name + '\'' +
                ", photoUrls=" + photoUrls +
                ", tags=" + tags +
                ", status='" + status + '\'' +
                '}';
    }
}
