package com.petstore.models;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class User {
    private long id;           // Unique identifier of the user
    private String username;   // Username of the user
    private String firstName;  // First name of the user
    private String lastName;   // Last name of the user
    private String email;      // Email address of the user
    private String password;   // Password of the user
    private String phone;      // Phone number of the user
    private int userStatus;    // User status (e.g., active, inactive, etc.)

    // Constructors, getters, and setters generated by Lombok

    @Override
    public String toString() {
        return "User{" +
                "id=" + id +
                ", username='" + username + '\'' +
                ", firstName='" + firstName + '\'' +
                ", lastName='" + lastName + '\'' +
                ", email='" + email + '\'' +
                ", password='" + password + '\'' +
                ", phone='" + phone + '\'' +
                ", userStatus=" + userStatus +
                '}';
    }
}
